jwt:
  secret:
    key: ${SECRET_KEY}

logging:
  ${ LOGGING_SETTING }

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # data.sql? ???? ??
    hibernate:
      ddl-auto: ${DDL_ENV}
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

gpt:
  model: gpt-3.5-turbo
  api:
    key:  ${GPT_API_KEY}
    url: https://api.openai.com/v1/chat/completions